name: cosmetics_lakehouse
version: "1.0.0"
config-version: 2

profile: cosmetics_lakehouse

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  cosmetics_lakehouse:
    +materialized: view
    staging:
      +schema: cosmetics_silver
      +materialized: incremental
      +incremental_strategy: append
      +on_schema_change: append_new_columns
      +file_format: iceberg
      +tblproperties:
        format-version: "2"
    gold:
      +schema: cosmetics_gold
      +materialized: incremental
      +incremental_strategy: append
      +on_schema_change: append_new_columns
      +file_format: iceberg
      +tblproperties:
        format-version: "2"